'''
Census backend: emits two walkers that describe the *same* AST two ways.

    census_gen.py    Python: walks the native AST through the pyext accessors
    census.ts        TS:     walks the tree the generated deserializer built

Both are emitted from one schema in one run, for the reason gen_wasm.py gives
about the serializer/deserializer pair: two walks that are supposed to produce
the same sequence, written separately, drift.


Why this exists
---------------

The parity fixtures that predate it (`gen-ast-parity-fixture.py`,
`gen-link-parity-fixture.py`) walk the **declaration spine** only -- `Scope` and
`SymbolChildrenScope` children, and on each node the name and location. That is
the containment structure, and it is where a node-built-as-the-wrong-class or a
subtree-attached-in-the-wrong-place defect shows up. It is also roughly a tenth
of the schema: it never descends into an expression, a constraint body or an
exec block, and it reads three fields per node out of the twenty-odd most
classes have. A serialisation defect confined to `ExprBin.op` passes it.

The census closes that. It visits every node the ownership graph reaches and
records every field, so it is the first gate that can fail on an expression.

Round-tripping the buffer would not do: both halves of the wire format are
generated from this same schema, so they agree with each other whether or not
they agree with the AST. The census's ground truth is the native AST read
through a *different* interface -- the Cython accessors -- so a defect in the
serializer, in the deserializer, or in the schema's description of a field has
somewhere to show up.


Why the Python side reads accessors rather than subclassing the visitor
-----------------------------------------------------------------------

The obvious instrument was a `VisitorBase` subclass on the native side. It does
not work: the generated visitor chains derived-to-base, so `visitExprId` calls
`visitExpr`, and the Cython wrapper is re-typed along the way -- `type(i).__name__`
inside `visitExpr` says `Expr` for an `ExprId`. A subclass therefore cannot tell
a node's own visit from a base class's, and every attempt to count by class
counts each node once per level of its inheritance chain.

Accessors have no such problem. `getExpr()` on a `ConstraintStmtExpr` returns an
`ExprBin`, most-derived, because the accessor dispatches through an ObjFactory
before wrapping. That is why the walk below is generated as one function per
class with the class's *flattened* field list inlined, and never calls a base
class's walker: each node is described exactly once, by name, with no chaining.


What is outside the census, and why
------------------------------------

**Map fields.** The pyext backend emits `<field>Has(k)` and `<field>At(k)` for a
map and nothing that enumerates keys (`pyext_map_accessor_gen.py`: `_hasKey`,
`_getItem`, and a `_getAsList` that is commented out). There is no way to read a
map's contents from Python, so the census cannot describe one. Five fields are
affected:

    SymbolImportSpec.symtab      map<string,UP<SymbolRefPath>>   <- the only one
    ExtendType.symtab            map<string,int32_t>                that owns
    SymbolScope.symtab           map<string,int32_t>
    RootSymbolScope.filenames    map<int32_t,string>
    RootSymbolScope.id2idx       map<int32_t,int32_t>

Maps are skipped by *both* walkers, in the body and in the ownership walk, so
the two sides stay aligned by construction. The consequence worth stating: the
`SymbolRefPath` nodes owned by `SymbolImportSpec.symtab` are reached only
through a map, so post-link they are outside the census entirely. Node ids here
are therefore the census's own, not the wire's.

Closing this needs a `<field>Keys()` accessor in the pyext backend and a rebuild
of the Cython extension -- an additive change to the shipped Python API, which
is more than a test instrument should decide on its own.

**64-bit and floating-point values** are compared as the hex of their IEEE-754
double bits. The TS reader already narrows int64/uint64 to `number` (gen_wasm.py
says why), so a value above 2^53 is not distinguishable on that side no matter
what the census does; encoding both sides through the same double makes the
comparison exact for everything that *is* representable and avoids the separate
problem that `json.dumps(1e-9)` is `1e-09` and `JSON.stringify(1e-9)` is `1e-9`.
'''

import os

from .ast_enum import AstEnum
from .ast_flags import AstFlags
from .ast_struct import AstStruct
from .gen_wasm import flat_fields, is_class_ref, is_owning
from .outstream import OutStream
from .type_list import TypeList
from .type_map import TypeMap
from .type_pointer import TypePointer
from .type_scalar import TypeKind, TypeScalar
from .type_userdef import TypeUserDef

PY_HEADER = "# Auto-generated by astbuilder gen-census - DO NOT EDIT\n"
TS_HEADER = "// Auto-generated by astbuilder gen-census - DO NOT EDIT\n"

#: Scalar kinds compared as IEEE-754 double bits rather than as JSON numbers.
#: See the module docstring.
_AS_DOUBLE = (TypeKind.Float32, TypeKind.Float64,
              TypeKind.Int64, TypeKind.Uint64)


class GenCensusError(Exception):
    pass


def walked(t):
    """True if the census's ownership walk descends through `t`.

    `is_owning` minus maps. The subtraction is the whole reason this predicate
    exists rather than calling `is_owning` directly: a map with owning values
    would be walked on the TS side and skipped on the Python side, the two id
    assignments would diverge at that node, and every record after it would be
    compared against the wrong node.
    """
    if isinstance(t, TypeMap):
        return False
    return is_owning(t)


def py_getter(d):
    """The pyext accessor for field `d`.

    Two rules, both transcribed from the pyext backend rather than guessed:
    `cpp_accessor_gen`-style capitalisation of the first character only, and
    `pyext_list_accessor_gen._getAsList`'s `List` suffix for a list whose name
    does not already read as a plural. That is why it is `getConstraints` but
    `getFileOutRefList`.
    """
    name = d.name[0].upper() + d.name[1:]
    if isinstance(d.t, TypeList):
        if not name.endswith("ren") and not name.endswith("s"):
            name += "List"
    return "get" + name


class GenCensus(object):

    def __init__(self, pydir, tsdir, license=None):
        self.pydir = pydir
        self.tsdir = tsdir
        self.license = license
        self.ast = None
        self._n = 0

    def _tmp(self, base):
        self._n += 1
        return "%s%d" % (base, self._n)

    def _write(self, d, name, out):
        if not os.path.isdir(d):
            os.makedirs(d)
        with open(os.path.join(d, name), "w") as f:
            f.write(out.content())

    def generate(self, ast):
        self.ast = ast
        self.generate_py()
        self.generate_ts()

    # ======================================================================
    # Python -- walks the native AST through the pyext accessors
    # ======================================================================

    def generate_py(self):
        out = OutStream()
        out.println(PY_HEADER.rstrip())
        out.write('''"""Describe a native pssparser AST as a flat record stream.

Companion to test/generated/census.ts, which does the same for the tree the
generated deserializer builds. See astbuilder/gen_census.py for what the two
cover and what they deliberately do not.
"""

import struct


def _f64(v):
    """IEEE-754 bits of `v` as 16 hex characters.

    Canonical in a way `repr` is not: Python prints 1e-09 where JavaScript
    prints 1e-9, and the two sides are compared as JSON text.
    """
    return struct.pack("<d", float(v)).hex()


class _Census(object):

    def __init__(self):
        self.ids = {}      # node identity -> census id
        self.order = []    # nodes in census id order

    def _ix(self, n):
        """Assign `n` an id and descend, unless it already has one.

        Identity is `hash(n)`, which the pyext backend defines as the wrapped
        `I<MostDerived>*` -- stable across wrappers and consistent across paths,
        because every wrapper for a node is built through the same most-derived
        class by ObjFactory.

        *Not* `n.id()`, which is the same value and reads better. A schema field
        named `id` shadows it: the list accessor emits `def id(self)` on
        PackageScope for its `list<UP<ExprId>>`, so `PackageScope.id()` returns
        a fresh ListUtil per call. Keyed on that, every PackageScope looked new
        on the second lookup, `_id` returned -1 for four of the standard
        library's five top-level children, and the already-seen guard was dead
        for those classes. `__hash__` cannot be shadowed by a field name.

        The guard itself mirrors AstIndexer::enter: a schema that grew a second
        owner for one node would otherwise give it two ids and desynchronise
        the walk.
        """
        if n is None:
            return
        k = hash(n)
        if k in self.ids:
            return
        self.ids[k] = len(self.order)
        self.order.append(n)
        _INDEX[type(n).__name__](self, n)

    def _id(self, n):
        """`n`'s census id, or -1 if it is null or outside the walked graph."""
        if n is None:
            return -1
        return self.ids.get(hash(n), -1)


def census(root):
    """Walk `root` and return {count, classes, records}.

    `records[k]` describes node k as `[className, ...field values]`, in the
    schema's flattened field order. `classes` is the count by class name, which
    turns a digest mismatch into something diagnosable without shipping the
    whole record stream.
    """
    c = _Census()
    c._ix(root)
    records = []
    classes = {}
    for n in c.order:
        name = type(n).__name__
        classes[name] = classes.get(name, 0) + 1
        r = [name]
        _BODY[name](c, n, r)
        records.append(r)
    return {"count": len(c.order), "classes": classes, "records": records}


''')
        self._emit_py_index(out)
        self._emit_py_body(out)
        self._write(self.pydir, "census_gen.py", out)

    def _emit_py_index(self, out):
        for c in self.ast.classes:
            out.println("def _ix_%s(c, n):" % c.name)
            out.inc_indent()
            fields = [d for d in flat_fields(c) if walked(d.t)]
            if not fields:
                out.println("pass")
            for d in fields:
                self._py_descend(out, d.t, "n.%s()" % py_getter(d))
            out.dec_indent()
            out.println()
        out.println("_INDEX = {")
        out.inc_indent()
        for c in self.ast.classes:
            out.println('"%s": _ix_%s,' % (c.name, c.name))
        out.dec_indent()
        out.println("}")
        out.println()

    def _py_descend(self, out, t, expr):
        if isinstance(t, TypePointer):
            out.println("c._ix(%s)" % expr)
        elif isinstance(t, TypeList):
            v = self._tmp("e")
            out.println("for %s in %s:" % (v, expr))
            out.inc_indent()
            self._py_descend(out, t.t, v)
            out.dec_indent()
        else:
            raise GenCensusError("not a walked type: %s" % type(t).__name__)

    def _emit_py_body(self, out):
        for c in self.ast.classes:
            out.println("def _bd_%s(c, n, r):" % c.name)
            out.inc_indent()
            fields = [d for d in flat_fields(c) if not isinstance(d.t, TypeMap)]
            if not fields:
                out.println("pass")
            for d in fields:
                self._py_field(out, d)
            out.dec_indent()
            out.println()
        out.println("_BODY = {")
        out.inc_indent()
        for c in self.ast.classes:
            out.println('"%s": _bd_%s,' % (c.name, c.name))
        out.dec_indent()
        out.println("}")
        out.println()

    def _py_field(self, out, d):
        t = d.t
        expr = "n.%s()" % py_getter(d)
        tgt = t.target if isinstance(t, TypeUserDef) else None
        if isinstance(tgt, AstStruct):
            # A struct is flattened into its fields rather than nested, so the
            # record stays a flat list of scalars and a diff points at one
            # field instead of one object.
            v = self._tmp("s")
            out.println("%s = %s" % (v, expr))
            for sd in tgt.data:
                out.println("r.append(%s)" % self._py_val(sd.t, "%s.%s" % (v, sd.name)))
        else:
            out.println("r.append(%s)" % self._py_val(t, expr))

    def _py_val(self, t, expr):
        if isinstance(t, TypeScalar):
            if t.t in _AS_DOUBLE:
                return "_f64(%s)" % expr
            return expr
        if is_class_ref(t):
            return "c._id(%s)" % expr
        if isinstance(t, TypeUserDef):
            tgt = t.target
            if isinstance(tgt, (AstEnum, AstFlags)):
                # int() rather than the value as returned: an IntEnum would
                # serialise as its name on one side and its number on the other.
                return "int(%s)" % expr
            if isinstance(tgt, AstStruct):
                # Nested rather than flattened, unlike at field level: inside a
                # container there is no fixed arity to flatten into, and a
                # flattened list of two-field structs is indistinguishable from
                # a list of twice as many scalars.
                return "[%s]" % ", ".join(
                    self._py_val(sd.t, "%s.%s" % (expr, sd.name)) for sd in tgt.data)
            raise GenCensusError("unresolved user type %s" % t.name)
        if isinstance(t, TypeList):
            v = self._tmp("e")
            if is_class_ref(t.t):
                # Unresolvable entries are dropped, not written as -1, because
                # that is what AstWriter does (gen_wasm.py explains) and the TS
                # tree therefore has no hole to describe.
                i = self._tmp("i")
                return "[%s for %s in (c._id(%s) for %s in %s) if %s >= 0]" % (
                    i, i, v, v, expr, i)
            return "[%s for %s in %s]" % (self._py_val(t.t, v), v, expr)
        raise GenCensusError("unhandled type %s" % type(t).__name__)

    # ======================================================================
    # TypeScript -- walks the tree the generated deserializer built
    # ======================================================================

    def generate_ts(self):
        out = OutStream()
        out.println(TS_HEADER.rstrip())
        out.write('''/*
 * Describe a deserialised AST as a flat record stream, to compare against the
 * fixture scripts/generated/census_gen.py writes from the native AST. See
 * astbuilder/gen_census.py for what the pair covers.
 *
 * This file lives under test/ rather than src/: it is an instrument, not part
 * of the published API, and tsconfig's rootDir would otherwise ship it.
 */

''')
        out.println("import * as cls from '../../src/ast/generated/classes.js';")
        out.println()
        out.write('''const _f = new DataView(new ArrayBuffer(8));

/* IEEE-754 bits as 16 hex characters -- see the Python half's _f64. */
function f64(v: number): string {
  _f.setFloat64(0, v, true);
  let s = '';
  for (let i = 0; i < 8; i++) {
    s += _f.getUint8(i).toString(16).padStart(2, '0');
  }
  return s;
}

/*
 * Constructor -> schema class name, rather than `constructor.name`.
 *
 * `.name` is a property of the function object, and a bundler that renames
 * classes would turn every record's first element into a mangled string while
 * leaving the counts intact -- a failure that reads as total divergence and is
 * nothing of the kind. The map is generated, so it cannot be renamed away.
 */
const NAME_OF = new Map<unknown, string>([
''')
        out.inc_indent()
        for c in self.ast.classes:
            out.println("[cls.%s, '%s']," % (c.name, c.name))
        out.dec_indent()
        out.println("]);")
        out.println()
        out.write('''type Node = Record<string, any>;

class Census {
  readonly ids = new Map<Node, number>();
  readonly order: Node[] = [];

  ix(n: Node | null | undefined): void {
    if (n === null || n === undefined || this.ids.has(n)) {
      return;
    }
    this.ids.set(n, this.order.length);
    this.order.push(n);
    const name = this.nameOf(n);
    INDEX[name]!(this, n);
  }

  id(n: Node | null | undefined): number {
    if (n === null || n === undefined) {
      return -1;
    }
    const i = this.ids.get(n);
    return i === undefined ? -1 : i;
  }

  nameOf(n: Node): string {
    const name = NAME_OF.get(n.constructor);
    if (name === undefined) {
      throw new Error(
        `census: ${String(n.constructor?.name)} is not a class of this schema`
      );
    }
    return name;
  }
}

export interface CensusResult {
  count: number;
  classes: Record<string, number>;
  records: unknown[][];
}

/**
 * Walk `root` and return the same {count, classes, records} shape the Python
 * half returns, with records in the same order and fields in the same order.
 */
export function census(root: unknown): CensusResult {
  const c = new Census();
  c.ix(root as Node);
  const records: unknown[][] = [];
  const classes: Record<string, number> = {};
  for (const n of c.order) {
    const name = c.nameOf(n);
    classes[name] = (classes[name] ?? 0) + 1;
    const r: unknown[] = [name];
    BODY[name]!(c, n, r);
    records.push(r);
  }
  return { count: c.order.length, classes, records };
}

''')
        self._emit_ts_index(out)
        self._emit_ts_body(out)
        self._write(self.tsdir, "census.ts", out)

    def _emit_ts_index(self, out):
        out.println("const INDEX: Record<string, (c: Census, n: Node) => void> = {")
        out.inc_indent()
        for c in self.ast.classes:
            fields = [d for d in flat_fields(c) if walked(d.t)]
            if not fields:
                out.println("%s: () => {}," % c.name)
                continue
            out.println("%s: (c, n) => {" % c.name)
            out.inc_indent()
            for d in fields:
                self._ts_descend(out, d.t, "n.%s" % d.name)
            out.dec_indent()
            out.println("},")
        out.dec_indent()
        out.println("};")
        out.println()

    def _ts_descend(self, out, t, expr):
        if isinstance(t, TypePointer):
            out.println("c.ix(%s);" % expr)
        elif isinstance(t, TypeList):
            v = self._tmp("e")
            out.println("for (const %s of %s) {" % (v, expr))
            out.inc_indent()
            self._ts_descend(out, t.t, v)
            out.dec_indent()
            out.println("}")
        else:
            raise GenCensusError("not a walked type: %s" % type(t).__name__)

    def _emit_ts_body(self, out):
        out.println("const BODY: Record<string, (c: Census, n: Node, r: unknown[]) => void> = {")
        out.inc_indent()
        for c in self.ast.classes:
            fields = [d for d in flat_fields(c) if not isinstance(d.t, TypeMap)]
            if not fields:
                out.println("%s: () => {}," % c.name)
                continue
            out.println("%s: (c, n, r) => {" % c.name)
            out.inc_indent()
            for d in fields:
                self._ts_field(out, d)
            out.dec_indent()
            out.println("},")
        out.dec_indent()
        out.println("};")
        out.println()

    def _ts_field(self, out, d):
        t = d.t
        expr = "n.%s" % d.name
        tgt = t.target if isinstance(t, TypeUserDef) else None
        if isinstance(tgt, AstStruct):
            for sd in tgt.data:
                out.println("r.push(%s);" % self._ts_val(sd.t, "%s.%s" % (expr, sd.name)))
        else:
            out.println("r.push(%s);" % self._ts_val(t, expr))

    def _ts_val(self, t, expr):
        if isinstance(t, TypeScalar):
            if t.t in _AS_DOUBLE:
                return "f64(%s)" % expr
            return expr
        if is_class_ref(t):
            return "c.id(%s)" % expr
        if isinstance(t, TypeUserDef):
            tgt = t.target
            if isinstance(tgt, (AstEnum, AstFlags)):
                return expr
            if isinstance(tgt, AstStruct):
                # Nested; see the Python half.
                return "[%s]" % ", ".join(
                    self._ts_val(sd.t, "%s.%s" % (expr, sd.name)) for sd in tgt.data)
            raise GenCensusError("unresolved user type %s" % t.name)
        if isinstance(t, TypeList):
            v = self._tmp("e")
            if is_class_ref(t.t):
                i = self._tmp("i")
                return ("%s.map((%s: Node) => c.id(%s)).filter((%s: number) => %s >= 0)"
                        % (expr, v, v, i, i))
            return "%s.map((%s: any) => %s)" % (expr, v, self._ts_val(t.t, v))
        raise GenCensusError("unhandled type %s" % type(t).__name__)
