'''
WASM-boundary backend: emits the two halves of the AST wire format.

    AstSerializer.h / .cpp    C++: AST -> flat buffer
    deserialize.ts            TS:  flat buffer -> gen-ts classes

The two halves are generated together, from one schema, in one run. That is the
whole point: a serializer and a deserializer that disagree about field order put
values in the wrong slots and every downstream symptom is baffling. Generating
them separately is how that happens.

The schema hash is NOT emitted here, even though `wasm-core-plan.md` §3.3 lists
it as this backend's output. It is produced by `pssparser/scripts/gen_schema_hash.py`,
which already runs in the WASM CMake configure step and the TS build, and it
does not depend on the wire format -- it knows only the schema's identity.
Emitting it from here as well would mean two producers of one file, which is
the failure mode the hash exists to catch.


The wire format
---------------

    u32   magic          0x50535331
    u32   nodeCount
    u16 x nodeCount      class tag, one per node, in id order
    ...   bodies         each node's fields, in id order
    u32   magic          repeated, so truncation is caught at the end

Node ids are assigned by a pre-order walk of the *ownership* graph -- UP<T>
fields, and containers whose element type is UP<T>. The root is id 0. Every
reference (owning or not) is written as an i32 id, with -1 for null and for a
raw pointer whose target is not in the serialised graph.

Bodies are emitted in id order because the tag table is written first, which
lets the reader construct every node before any field is filled. There is no
fixup pass and no forward-reference bookkeeping on either side.

Not versioned. The schema hash makes versioning unnecessary -- the two ends
ship together and a mismatch is a load-time error, not a decoding problem.


Why two visitors rather than a node list
----------------------------------------

The C++ half is a pair of generated IVisitor implementations that perform the
*same* walk: the indexer assigns an id and recurses, the writer emits a body and
recurses. Body k therefore lands at id k with nothing recorded between the two
passes except the id map.

The alternative -- index into a `std::vector<node*>` and iterate it -- needs a
common pointer type for dispatch, and this hierarchy has none: 15 unrelated
roots, and the generated classes use virtual multiple inheritance, so an
upcast pointer is not even a stable identity. (That last point is why the id
map is keyed on `dynamic_cast<void*>`, which yields the most-derived address.)
'''

import os

from .ast_class import AstClass
from .ast_enum import AstEnum
from .ast_flags import AstFlags
from .ast_struct import AstStruct
from .outstream import OutStream
from .type_list import TypeList
from .type_map import TypeMap
from .type_pointer import PointerKind, TypePointer
from .type_scalar import TypeKind, TypeScalar
from .type_userdef import TypeUserDef

HEADER = "// Auto-generated by astbuilder gen-wasm - DO NOT EDIT\n"

MAGIC = 0x50535331

# TypeKind -> (C++ Buf method, TS Reader method)
#
# Every kind is listed, and the two columns are read off the same row so they
# cannot drift in width. A missing row is a generator error rather than a
# fallthrough: silently writing a uint16_t as a u32 is decodable garbage.
_SCALAR = {
    TypeKind.String:  ("str", "str"),
    TypeKind.Bool:    ("b",   "bool"),
    TypeKind.Int8:    ("i8",  "i8"),
    TypeKind.Uint8:   ("u8",  "u8"),
    TypeKind.Int16:   ("i16", "i16"),
    TypeKind.Uint16:  ("u16", "u16"),
    TypeKind.Int32:   ("i32", "i32"),
    TypeKind.Uint32:  ("u32", "u32"),
    TypeKind.Int64:   ("i64", "i64"),
    TypeKind.Uint64:  ("u64", "u64"),
    TypeKind.Float32: ("f32", "f32"),
    TypeKind.Float64: ("f64", "f64"),
}


class GenWasmError(Exception):
    pass


# -- schema queries ---------------------------------------------------------

def flat_fields(c):
    """Every field of `c`, base class first.

    Base-first is not a preference: the reader assigns into a constructed
    instance and the writer reads off accessors, so the two only have to agree
    with *each other*. Matching gen_cpp's constructor order anyway keeps the
    emitted code legible next to the class it serialises.
    """
    ret = []
    if c.super is not None and c.super.target is not None:
        ret.extend(flat_fields(c.super.target))
    ret.extend(c.data)
    return ret


def is_class_ref(t):
    """True if `t` denotes a reference to an AST class (pointer or bare)."""
    if isinstance(t, TypePointer):
        return True
    return isinstance(t, TypeUserDef) and isinstance(t.target, AstClass)


def is_owning(t):
    """True if `t` conveys ownership, and so is walked to assign ids.

    Raw pointers are excluded. They are back- and cross-references -- `parent`,
    `imports`, the resolved `target` of a reference -- and their targets are
    owned somewhere else in the tree. Walking them would assign a second id to
    an already-visited node, or wander into a different compilation unit.
    """
    if isinstance(t, TypePointer):
        return t.pt in (PointerKind.Unique, PointerKind.Shared)
    if isinstance(t, TypeList):
        return is_owning(t.t)
    if isinstance(t, TypeMap):
        return is_owning(t.vt)
    return False


def getter(d):
    """The generated C++ accessor for field `d`.

    cpp_accessor_gen.py:69 upper-cases the first character and leaves the rest
    alone, so `trailing_comments` becomes `getTrailing_comments`. Reproducing
    the rule rather than title-casing is the difference between compiling and
    not.
    """
    return "get" + d.name[0].upper() + d.name[1:]


class GenWasm(object):

    def __init__(self, cppdir, tsdir, license=None):
        self.cppdir = cppdir
        self.tsdir = tsdir
        self.license = license
        self.ast = None
        self.tag_of = {}
        self._n = 0

    # -- helpers ------------------------------------------------------------

    def _tmp(self, base):
        self._n += 1
        return "%s%d" % (base, self._n)

    def _open(self):
        out = OutStream()
        out.println(HEADER.rstrip())
        if self.license is not None:
            # etc/copyright.cpp is a comment *body* -- every line already
            # carries a ` *` prefix and there is no delimiter at either end --
            # so it has to be wrapped. gen_cpp wraps it too; emitting it raw is
            # how it reached the head of a file as a syntax error.
            out.println("/*")
            out.write(self.license.rstrip("\n"))
            out.println()
            out.println(" */")
        out.println()
        return out

    def _write(self, d, name, out):
        if not os.path.isdir(d):
            os.makedirs(d)
        with open(os.path.join(d, name), "w") as f:
            f.write(out.content())

    # -- entry point --------------------------------------------------------

    def generate(self, ast):
        self.ast = ast
        # The tag is the class's index in ast.classes, which Linker sorts
        # topologically and Parser sorts by name beforehand -- deterministic
        # across runs, and covered by the schema hash if the schema moves.
        self.tag_of = {c.name: i for i, c in enumerate(ast.classes)}

        self.generate_cpp_header()
        self.generate_cpp_source()
        self.generate_ts()

    # ======================================================================
    # C++
    # ======================================================================

    def generate_cpp_header(self):
        out = self._open()
        out.println("#pragma once")
        out.println("#include <stdint.h>")
        out.println("#include <string>")
        out.println("#include <unordered_map>")
        out.println("#include <vector>")
        out.println('#include "pssp/ast/IVisitor.h"')
        out.println()
        out.println("namespace pssp {")
        out.println("namespace ast {")
        out.println()
        out.println("/**")
        out.println(" * Serialise an AST rooted at `root` into the wire format described in")
        out.println(" * astbuilder/gen_wasm.py.")
        out.println(" *")
        out.println(" * A template because this hierarchy has no common base -- the schema has")
        out.println(" * %d root classes -- and the only thing needed of `T` is accept()." %
                    len(self.ast.rootClasses()))
        out.println(" *")
        out.println(" * Returns a std::string used as a byte container, which is what Embind")
        out.println(" * marshals to a JS string/Uint8Array in one copy. It is not text.")
        out.println(" */")
        out.println("std::string serializeAstImpl(IVisitor *indexer, IVisitor *writer);")
        out.println()
        out.println("IVisitor *mkAstIndexer();")
        out.println("IVisitor *mkAstWriter(IVisitor *indexer);")
        out.println("std::string takeAstBuffer(IVisitor *indexer, IVisitor *writer);")
        out.println()
        out.println("template <class T> std::string serializeAst(T *root) {")
        out.inc_indent()
        out.println("IVisitor *indexer = mkAstIndexer();")
        out.println("if (root) {")
        out.inc_indent()
        out.println("root->accept(indexer);")
        out.dec_indent()
        out.println("}")
        out.println("IVisitor *writer = mkAstWriter(indexer);")
        out.println("if (root) {")
        out.inc_indent()
        out.println("root->accept(writer);")
        out.dec_indent()
        out.println("}")
        out.println("return takeAstBuffer(indexer, writer);")
        out.dec_indent()
        out.println("}")
        out.println()
        out.println("} // namespace ast")
        out.println("} // namespace pssp")
        self._write(self.cppdir, "AstSerializer.h", out)

    def generate_cpp_source(self):
        out = self._open()
        out.println('#include "AstSerializer.h"')
        out.println()
        out.println("#include <algorithm>")
        out.println("#include <string.h>")
        out.println("#include <utility>")
        out.println()
        for c in self.ast.classes:
            out.println('#include "pssp/ast/I%s.h"' % c.name)
        out.println()
        out.println("namespace pssp {")
        out.println("namespace ast {")
        out.println("namespace {")
        out.println()
        self._emit_cpp_buf(out)
        self._emit_cpp_indexer(out)
        self._emit_cpp_writer(out)
        out.println("} // namespace")
        out.println()
        self._emit_cpp_entrypoints(out)
        out.println("} // namespace ast")
        out.println("} // namespace pssp")
        self._write(self.cppdir, "AstSerializer.cpp", out)

    def _emit_cpp_buf(self, out):
        out.write('''/*
 * Little-endian, unaligned, no padding. Unaligned because the reader is a
 * DataView, which does not care, and aligning would mean emitting and skipping
 * pad bytes symmetrically on two sides -- one more thing to get wrong for a
 * gain that is not measurable against a 550 MiB/s boundary.
 */
struct Buf {
    std::vector<uint8_t> d;

    void raw(const void *p, size_t n) {
        const uint8_t *b = static_cast<const uint8_t *>(p);
        d.insert(d.end(), b, b + n);
    }

    void u8(uint8_t v)   { d.push_back(v); }
    void i8(int8_t v)    { d.push_back(static_cast<uint8_t>(v)); }
    void u16(uint16_t v) { raw(&v, 2); }
    void i16(int16_t v)  { raw(&v, 2); }
    void u32(uint32_t v) { raw(&v, 4); }
    void i32(int32_t v)  { raw(&v, 4); }
    void u64(uint64_t v) { raw(&v, 8); }
    void i64(int64_t v)  { raw(&v, 8); }
    void f32(float v)    { raw(&v, 4); }
    void f64(double v)   { raw(&v, 8); }
    void b(bool v)       { d.push_back(v ? 1 : 0); }

    /* u32 byte length, then UTF-8 bytes. std::string is already UTF-8 here:
     * the lexer reads UTF-8 source and never transcodes. */
    void str(const std::string &s) {
        u32(static_cast<uint32_t>(s.size()));
        if (!s.empty()) {
            raw(s.data(), s.size());
        }
    }
};

''')

    # -- indexer ------------------------------------------------------------

    def _emit_cpp_indexer(self, out):
        out.write('''/*
 * Pass 1: assign an id to every owned node, in pre-order.
 *
 * Identity is `dynamic_cast<void*>`, not the incoming pointer. The generated
 * classes use virtual multiple inheritance -- `class Scope : public virtual
 * IScope, public ScopeChild` -- so the same object reached as IScope* and as
 * IScopeChild* has two different addresses, and a map keyed on either would
 * fail to recognise a node it had already seen.
 */
class AstIndexer : public IVisitor {
public:
    std::unordered_map<void *, int32_t> ids;
    std::vector<uint16_t>               tags;

    template <class T> int32_t idOf(T *p) const {
        if (!p) {
            return -1;
        }
        std::unordered_map<void *, int32_t>::const_iterator it =
            ids.find(dynamic_cast<void *>(p));
        return (it == ids.end()) ? -1 : it->second;
    }

private:
    /* False if this node has been seen already, which the caller takes as
     * "do not recurse". A well-formed AST never hits it -- ownership is a
     * tree -- but a schema that grew a second owner for one node would
     * otherwise produce two ids for it and desynchronise the writer. */
    template <class T> bool enter(T *n, uint16_t tag) {
        void *k = dynamic_cast<void *>(n);
        if (ids.find(k) != ids.end()) {
            return false;
        }
        ids[k] = static_cast<int32_t>(tags.size());
        tags.push_back(tag);
        return true;
    }

public:
''')
        out.inc_indent()
        for c in self.ast.classes:
            out.println("void visit%s(I%s *i) override {" % (c.name, c.name))
            out.inc_indent()
            out.println("if (!enter(i, %d)) { return; }" % self.tag_of[c.name])
            for d in flat_fields(c):
                if is_owning(d.t):
                    self._descend_cpp(out, d.t, "i->%s()" % getter(d), False)
            out.dec_indent()
            out.println("}")
        out.dec_indent()
        out.println("};")
        out.println()

    def _descend_cpp(self, out, t, expr, in_container):
        """Emit the indexer's recursion into an owning field."""
        if isinstance(t, TypePointer):
            ptr = "%s.get()" % expr if in_container else expr
            v = self._tmp("n")
            out.println("{ auto *%s = %s; if (%s) { %s->accept(this); } }" % (v, ptr, v, v))
        elif isinstance(t, TypeList):
            v = self._tmp("e")
            out.println("for (auto &%s : %s) {" % (v, expr))
            out.inc_indent()
            self._descend_cpp(out, t.t, v, True)
            out.dec_indent()
            out.println("}")
        elif isinstance(t, TypeMap):
            v = self._tmp("kv")
            out.println("for (auto &%s : %s) {" % (v, expr))
            out.inc_indent()
            self._descend_cpp(out, t.vt, "%s.second" % v, True)
            out.dec_indent()
            out.println("}")
        else:
            raise GenWasmError("not an owning type: %s" % type(t).__name__)

    # -- writer -------------------------------------------------------------

    def _emit_cpp_writer(self, out):
        out.write('''/*
 * Pass 2: emit each node's body, walking the ownership graph in exactly the
 * order the indexer did. Body k is therefore node k, and nothing has to be
 * recorded between the passes beyond the id map.
 *
 * The `written` guard mirrors AstIndexer::enter for the same reason: if the
 * indexer skipped a node the writer must skip it too, or the two orders
 * diverge and every subsequent body is misfiled.
 */
class AstWriter : public IVisitor {
public:
    AstWriter(const AstIndexer &idx) : m_idx(idx), m_written(idx.tags.size(), false) { }

    Buf buf;

private:
    const AstIndexer   &m_idx;
    std::vector<bool>   m_written;

    template <class T> int32_t idOf(T *p) const { return m_idx.idOf(p); }

    template <class T> bool enter(T *n) {
        int32_t id = m_idx.idOf(n);
        if (id < 0 || m_written[id]) {
            return false;
        }
        m_written[id] = true;
        return true;
    }

public:
''')
        out.inc_indent()
        for c in self.ast.classes:
            out.println("void visit%s(I%s *i) override {" % (c.name, c.name))
            out.inc_indent()
            out.println("if (!enter(i)) { return; }")
            fields = flat_fields(c)
            for d in fields:
                self._write_cpp(out, d.t, "i->%s()" % getter(d), False)
            # Recurse *after* the body, in field order: pre-order, same as the
            # indexer.
            for d in fields:
                if is_owning(d.t):
                    self._descend_cpp(out, d.t, "i->%s()" % getter(d), False)
            out.dec_indent()
            out.println("}")
        out.dec_indent()
        out.println("};")
        out.println()

    def _write_cpp(self, out, t, expr, in_container):
        if isinstance(t, TypeScalar):
            out.println("buf.%s(%s);" % (_SCALAR[t.t][0], expr))
        elif is_class_ref(t):
            ptr = "%s.get()" % expr if (in_container and isinstance(t, TypePointer)
                                        and t.pt != PointerKind.Raw) else expr
            out.println("buf.i32(idOf(%s));" % ptr)
        elif isinstance(t, TypeUserDef):
            tgt = t.target
            if isinstance(tgt, (AstEnum, AstFlags)):
                out.println("buf.i32(static_cast<int32_t>(%s));" % expr)
            elif isinstance(tgt, AstStruct):
                for d in tgt.data:
                    self._write_cpp(out, d.t, "%s.%s" % (expr, d.name), False)
            else:
                raise GenWasmError("unresolved user type %s" % t.name)
        elif isinstance(t, TypeList):
            self._write_cpp_list(out, t, expr)
        elif isinstance(t, TypeMap):
            self._write_cpp_map(out, t, expr)
        else:
            raise GenWasmError("unhandled type %s" % type(t).__name__)

    def _write_cpp_list(self, out, t, expr):
        elem_is_ref = is_class_ref(t.t)
        v = self._tmp("e")
        ref = self._tmp("r")
        out.println("{")
        out.inc_indent()
        out.println("const auto &%s = %s;" % (ref, expr))
        if elem_is_ref:
            # Entries that resolve to no id are dropped rather than written as
            # -1. The generated TypeScript element type is non-nullable --
            # `list<UP<Expr>>` is `Expr[]`, not `(Expr | null)[]`, because a
            # hole is not a state the C++ AST can represent -- so a null would
            # have to be invented on the reading side. Dropping is lossy for a
            # raw-pointer list whose target is in another compilation unit;
            # that loss is real and has nowhere to go, since the other unit is
            # not in this buffer.
            cnt = self._tmp("n")
            out.println("uint32_t %s = 0;" % cnt)
            out.println("for (auto &%s : %s) { if (idOf(%s) >= 0) { %s++; } }" % (
                v, ref, self._elem_ptr(t.t, v), cnt))
            out.println("buf.u32(%s);" % cnt)
            eid = self._tmp("id")
            out.println("for (auto &%s : %s) {" % (v, ref))
            out.inc_indent()
            out.println("int32_t %s = idOf(%s);" % (eid, self._elem_ptr(t.t, v)))
            out.println("if (%s >= 0) { buf.i32(%s); }" % (eid, eid))
            out.dec_indent()
            out.println("}")
        else:
            out.println("buf.u32(static_cast<uint32_t>(%s.size()));" % ref)
            out.println("for (auto &%s : %s) {" % (v, ref))
            out.inc_indent()
            self._write_cpp(out, t.t, v, True)
            out.dec_indent()
            out.println("}")
        out.dec_indent()
        out.println("}")

    def _elem_ptr(self, t, v):
        if isinstance(t, TypePointer) and t.pt != PointerKind.Raw:
            return "%s.get()" % v
        return v

    def _write_cpp_map(self, out, t, expr):
        # Sorted by key. The C++ side is std::unordered_map, whose iteration
        # order is an implementation detail; emitting it verbatim would make
        # the buffer non-reproducible and the resulting JS Map's insertion
        # order arbitrary. Sorting costs a vector of pointers per map, and the
        # schema has four of them.
        ref = self._tmp("m")
        ents = self._tmp("ents")
        kv = self._tmp("kv")
        val_is_ref = is_class_ref(t.vt)
        out.println("{")
        out.inc_indent()
        out.println("const auto &%s = %s;" % (ref, expr))
        out.println("std::vector<const typename std::remove_reference<"
                    "decltype(%s)>::type::value_type *> %s;" % (ref, ents))
        out.println("%s.reserve(%s.size());" % (ents, ref))
        out.println("for (auto &%s : %s) { %s.push_back(&%s); }" % (kv, ref, ents, kv))
        out.println("std::sort(%s.begin(), %s.end(), [](const auto *a, const auto *b) "
                    "{ return a->first < b->first; });" % (ents, ents))
        e = self._tmp("e")
        if val_is_ref:
            cnt = self._tmp("n")
            out.println("uint32_t %s = 0;" % cnt)
            out.println("for (auto *%s : %s) { if (idOf(%s) >= 0) { %s++; } }" % (
                e, ents, self._elem_ptr(t.vt, "%s->second" % e), cnt))
            out.println("buf.u32(%s);" % cnt)
            vid = self._tmp("id")
            out.println("for (auto *%s : %s) {" % (e, ents))
            out.inc_indent()
            out.println("int32_t %s = idOf(%s);" % (
                vid, self._elem_ptr(t.vt, "%s->second" % e)))
            out.println("if (%s < 0) { continue; }" % vid)
            self._write_cpp(out, t.kt, "%s->first" % e, True)
            out.println("buf.i32(%s);" % vid)
            out.dec_indent()
            out.println("}")
        else:
            out.println("buf.u32(static_cast<uint32_t>(%s.size()));" % ents)
            out.println("for (auto *%s : %s) {" % (e, ents))
            out.inc_indent()
            self._write_cpp(out, t.kt, "%s->first" % e, True)
            self._write_cpp(out, t.vt, "%s->second" % e, True)
            out.dec_indent()
            out.println("}")
        out.dec_indent()
        out.println("}")

    # -- entry points -------------------------------------------------------

    def _emit_cpp_entrypoints(self, out):
        out.write('''IVisitor *mkAstIndexer() {
    return new AstIndexer();
}

IVisitor *mkAstWriter(IVisitor *indexer) {
    return new AstWriter(*static_cast<AstIndexer *>(indexer));
}

/*
 * Assemble header + tag table + bodies, and take ownership of both visitors.
 *
 * The tag table is written before any body so the reader can construct every
 * node up front. That is what removes the fixup pass: a reference field can
 * name a node that has not been decoded yet, and the reader still has an
 * object to point at.
 */
std::string takeAstBuffer(IVisitor *indexer, IVisitor *writer) {
    AstIndexer *idx = static_cast<AstIndexer *>(indexer);
    AstWriter  *w   = static_cast<AstWriter *>(writer);

    Buf head;
    head.u32(%(magic)su);
    head.u32(static_cast<uint32_t>(idx->tags.size()));
    for (size_t i = 0; i < idx->tags.size(); i++) {
        head.u16(idx->tags[i]);
    }

    /* Repeated at the end so a truncated transfer fails at decode rather than
     * producing a short but well-formed-looking tree. */
    w->buf.u32(%(magic)su);

    std::string ret;
    ret.reserve(head.d.size() + w->buf.d.size());
    ret.append(reinterpret_cast<const char *>(head.d.data()), head.d.size());
    ret.append(reinterpret_cast<const char *>(w->buf.d.data()), w->buf.d.size());

    delete w;
    delete idx;
    return ret;
}

''' % {"magic": "0x%08X" % MAGIC})

    # ======================================================================
    # TypeScript
    # ======================================================================

    def generate_ts(self):
        out = self._open()
        out.write('''/*
 * The reading half of the AST wire format. See astbuilder/gen_wasm.py for the
 * format itself; the two halves are emitted from one schema in one run.
 */
''')
        out.println("import * as cls from './classes.js';")
        out.println("import * as enums from './enums.js';")
        out.println("import * as flags from './flags.js';")
        if self.ast.structs:
            out.println("import { %s } from './structs.js';" % ", ".join(
                "mk%s" % s.name for s in self.ast.structs))
        out.println()
        out.println("const MAGIC = 0x%08X;" % MAGIC)
        out.println()
        out.write('''/**
 * Any node this schema can produce.
 *
 * A union of the schema's root classes rather than of all %(nclasses)d: every class
 * derives from one of them, so the union already denotes "an AST node" and
 * stays legible.
 */
''' % {"nclasses": len(self.ast.classes)})
        out.println("export type AstNode =")
        out.inc_indent()
        roots = sorted(c.name for c in self.ast.rootClasses())
        for i, name in enumerate(roots):
            out.println("| cls.%s%s" % (name, ";" if i == len(roots) - 1 else ""))
        out.dec_indent()
        out.println()
        self._emit_ts_reader(out)
        self._emit_ts_ctors(out)
        self._emit_ts_readers(out)
        self._emit_ts_deserialize(out)
        self._write(self.tsdir, "deserialize.ts", out)

    def _emit_ts_reader(self, out):
        out.write('''class Reader {
  off = 0;

  constructor(
    private readonly view: DataView,
    private readonly bytes: Uint8Array
  ) {}

  u8(): number { return this.view.getUint8(this.off++); }
  i8(): number { return this.view.getInt8(this.off++); }
  u16(): number { const v = this.view.getUint16(this.off, true); this.off += 2; return v; }
  i16(): number { const v = this.view.getInt16(this.off, true); this.off += 2; return v; }
  u32(): number { const v = this.view.getUint32(this.off, true); this.off += 4; return v; }
  i32(): number { const v = this.view.getInt32(this.off, true); this.off += 4; return v; }
  f32(): number { const v = this.view.getFloat32(this.off, true); this.off += 4; return v; }
  f64(): number { const v = this.view.getFloat64(this.off, true); this.off += 8; return v; }
  bool(): boolean { return this.view.getUint8(this.off++) !== 0; }

  /*
   * 64-bit fields are read as BigInt and narrowed to `number`, because that is
   * the type gen-ts gives them and widening it here would change the AST's
   * public shape for three fields. Values beyond 2^53 lose precision -- the
   * schema's uint64 field is ExprUnsignedNumber.value, so a PSS literal above
   * 9007199254740991 is affected. The alternative, a bigint-typed field, would
   * make every arithmetic consumer handle a type it never sees in practice.
   */
  u64(): number { const v = this.view.getBigUint64(this.off, true); this.off += 8; return Number(v); }
  i64(): number { const v = this.view.getBigInt64(this.off, true); this.off += 8; return Number(v); }

  str(): string {
    const n = this.u32();
    if (n === 0) return '';
    const s = DECODER.decode(this.bytes.subarray(this.off, this.off + n));
    this.off += n;
    return s;
  }
}

const DECODER = new TextDecoder('utf-8', { fatal: true });

/*
 * `any` is load-bearing here rather than lazy. The wire carries a class tag per
 * node and the reader resolves a reference by index into a heterogeneous array;
 * that the id at this field belongs to a node of the field's declared type is a
 * property of the schema both halves were generated from, and is not one the
 * type system can be shown.
 */
function ref(nodes: any[], id: number): any {
  return id < 0 ? null : nodes[id];
}

''')

    def _emit_ts_ctors(self, out):
        out.println("/* Tag -> constructor, indexed by the class's position in the schema. */")
        out.println("const CTORS: Array<new () => any> = [")
        out.inc_indent()
        for c in self.ast.classes:
            out.println("cls.%s," % c.name)
        out.dec_indent()
        out.println("];")
        out.println()

    def _emit_ts_readers(self, out):
        out.println("/* Tag -> body reader. Field order matches AstWriter exactly. */")
        out.println("const READERS: Array<(r: Reader, n: any, nodes: any[]) => void> = [")
        out.inc_indent()
        for c in self.ast.classes:
            out.println("// %s" % c.name)
            out.println("(r, n, nodes) => {")
            out.inc_indent()
            fields = flat_fields(c)
            if not fields:
                out.println("void r; void n; void nodes;")
            for d in fields:
                self._read_ts(out, d.t, "n.%s" % d.name)
            out.dec_indent()
            out.println("},")
        out.dec_indent()
        out.println("];")
        out.println()

    def _read_ts(self, out, t, lhs):
        """Emit statements that assign one decoded value of `t` to `lhs`.

        Statements rather than an expression because lists and maps need a
        loop, and mixing the two forms would mean every caller handling both.
        """
        if isinstance(t, TypeScalar):
            out.println("%s = r.%s();" % (lhs, _SCALAR[t.t][1]))
        elif is_class_ref(t):
            out.println("%s = ref(nodes, r.i32());" % lhs)
        elif isinstance(t, TypeUserDef):
            tgt = t.target
            if isinstance(tgt, AstEnum):
                out.println("%s = r.i32() as enums.%s;" % (lhs, t.name))
            elif isinstance(tgt, AstFlags):
                out.println("%s = r.i32() as flags.%s;" % (lhs, t.name))
            elif isinstance(tgt, AstStruct):
                out.println("%s = %s;" % (lhs, self._read_ts_struct(tgt)))
            else:
                raise GenWasmError("unresolved user type %s" % t.name)
        elif isinstance(t, TypeList):
            n = self._tmp("n")
            a = self._tmp("a")
            i = self._tmp("i")
            out.println("{")
            out.inc_indent()
            out.println("const %s = r.u32();" % n)
            out.println("const %s: any[] = [];" % a)
            out.println("for (let %s = 0; %s < %s; %s++) {" % (i, i, n, i))
            out.inc_indent()
            el = self._tmp("v")
            out.println("let %s: any;" % el)
            self._read_ts(out, t.t, el)
            out.println("%s.push(%s);" % (a, el))
            out.dec_indent()
            out.println("}")
            out.println("%s = %s;" % (lhs, a))
            out.dec_indent()
            out.println("}")
        elif isinstance(t, TypeMap):
            n = self._tmp("n")
            m = self._tmp("m")
            i = self._tmp("i")
            out.println("{")
            out.inc_indent()
            out.println("const %s = r.u32();" % n)
            out.println("const %s = new Map<any, any>();" % m)
            out.println("for (let %s = 0; %s < %s; %s++) {" % (i, i, n, i))
            out.inc_indent()
            k = self._tmp("k")
            v = self._tmp("v")
            out.println("let %s: any;" % k)
            self._read_ts(out, t.kt, k)
            out.println("let %s: any;" % v)
            self._read_ts(out, t.vt, v)
            out.println("%s.set(%s, %s);" % (m, k, v))
            out.dec_indent()
            out.println("}")
            out.println("%s = %s;" % (lhs, m))
            out.dec_indent()
            out.println("}")
        else:
            raise GenWasmError("unhandled type %s" % type(t).__name__)

    def _read_ts_struct(self, s):
        """A struct is decoded as one mk<Name>(...) call.

        JavaScript evaluates arguments left to right, so the reads happen in
        declaration order -- which is the order AstWriter emitted them.
        """
        args = []
        for d in s.data:
            if isinstance(d.t, TypeScalar):
                args.append("r.%s()" % _SCALAR[d.t.t][1])
            elif isinstance(d.t, TypeUserDef) and isinstance(d.t.target, AstEnum):
                args.append("r.i32() as enums.%s" % d.t.name)
            elif isinstance(d.t, TypeUserDef) and isinstance(d.t.target, AstFlags):
                args.append("r.i32() as flags.%s" % d.t.name)
            else:
                raise GenWasmError(
                    "struct %s field %s: only scalar and enum struct fields are "
                    "supported by the wire format" % (s.name, d.name))
        return "mk%s(%s)" % (s.name, ", ".join(args))

    def _emit_ts_deserialize(self, out):
        out.write('''/**
 * Decode a serialised AST. Returns the root node, or null for an empty buffer.
 *
 * Throws on anything that is not a well-formed buffer for *this* schema. That
 * is deliberate: the schema hash is checked once at module load, so a decode
 * failure here means a genuine corruption or a truncated transfer, and a
 * partially-built tree returned quietly would be far worse than an exception.
 */
export function deserialize(bytes: Uint8Array): AstNode | null {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const r = new Reader(view, bytes);

  if (bytes.byteLength < 8) {
    throw new Error(`serialised AST is too short: ${bytes.byteLength} bytes`);
  }
  const magic = r.u32();
  if (magic !== MAGIC) {
    throw new Error(
      `serialised AST has bad magic 0x${magic.toString(16)} (expected 0x${MAGIC.toString(16)})`
    );
  }

  const count = r.u32();
  if (count === 0) {
    return null;
  }

  // Every node is constructed before any field is read, which is what lets a
  // reference name a node that has not been decoded yet. No fixup pass.
  const tags = new Array<number>(count);
  const nodes = new Array<any>(count);
  for (let i = 0; i < count; i++) {
    const tag = r.u16();
    const ctor = CTORS[tag];
    if (ctor === undefined) {
      throw new Error(`serialised AST has unknown class tag ${tag} at node ${i}`);
    }
    tags[i] = tag;
    nodes[i] = new ctor();
  }

  for (let i = 0; i < count; i++) {
    READERS[tags[i]!]!(r, nodes[i], nodes);
  }

  const trailer = r.u32();
  if (trailer !== MAGIC) {
    throw new Error('serialised AST is truncated or misaligned: bad trailer');
  }
  if (r.off !== bytes.byteLength) {
    // Reaching a correct trailer without consuming the buffer means the two
    // halves disagree about a field width somewhere upstream of it.
    throw new Error(
      `serialised AST left ${bytes.byteLength - r.off} trailing bytes unread`
    );
  }

  return nodes[0] as AstNode;
}
''')
